### ISSUE TITLE
[Puppy-reinforcement] Change image size

### ISSUE THREAD

**Issue by pavelandreievich** [glutanimate/puppy-reinforcement#11]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

Is it possible to change the image size when it appears in Anki? I want to the images to be a little bit larger but I don't know the code to do this. 
I was able to alter the code so that the box itself is larger, but I can't seem to figure out how to make the images larger.

**Comment by glutanimate** [comment]
Hey pavel! Sorry for taking so long to respond. In the upcoming 2.1 release of the add-on you will be able to adjust the image size by changing the "image_height" option in the add-on's configuration under Tools → Add-ons → double click on "Puppy Reinforcement" in the list. You can follow along with the progress on the 2.1 release here: https://github.com/glutanimate/puppy-reinforcement/issues/5
