### ISSUE TITLE
also use in Add Card dialog

### ISSUE THREAD

**Issue by ijgnd** [glutanimate/puppy-reinforcement#12]
in the anki subreddit /u/xTheKezio [wrote](https://www.reddit.com/r/Anki/comments/eldpdq/looking_for_an_addon_like_the_puppy_reinforcement/):

> I easily get distracted when im making new flashcards whenever i need to come up with a specific question myself. Making specific questions is pretty hard so I instantly get de-motivated. If whenever I hit "ctrl+enter" a puppy would show-up then maybe it would get a little more bearable.

This sounds like a useful extension. 

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that this feature is not in this github repo.
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

**Comment by glutanimate** [comment]
Sounds like a cool idea! Not something I'd be able to work on straight away, but if anyone wants to file a  PR in the meantime, I'd be more than happy to merge it.

**Comment by glutanimate** [comment]
This is now available in the current development branch, all thanks to @zjosua !

**Comment by glutanimate** [comment]
(and of course thanks to you, @ijgnd, for triaging this :+1: )
