### ISSUE TITLE
Arguments did not match any overloaded call

### ISSUE THREAD

**Issue by GrimPixel** [glutanimate/puppy-reinforcement#25]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

When the puppies are supposed to show up, this error occurs.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x ] I've restarted Anki to see if it helps
 - [ x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*
    
    Anki 2.1.50 (81cc5a09) Python 3.10.1 Qt 5.15.2 PyQt 5.15.6
    Platform: Linux
    Flags: frz=False ao=False sv=2
    Add-ons, last update check: 2022-01-24 08:16:04
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Puppy Reinforcement ['1722658993', 2020-03-02T20:23, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1722658993
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2021-12-05T02:31, 'None', '']
    Add Table ['1237621971', 2021-12-05T20:27, 'None', '']
    Adjust Sound Volume ['2123044452', 2021-05-05T12:24, 'None', '']
    Advanced Browser ['874215009', 2022-01-19T17:15, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-05-03T19:46, 'None', '']
    Allows empty first field during adding and import ['46741504', 2021-10-17T22:27, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T20:24, 'None', '']
    Anki Speed Limit ['395996975', 2021-03-23T13:03, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T01:20, 'v1.1.3', mod]
    AnkiConnect ['2055492159', 2021-12-27T06:22, 'None', '']
    Ankimote - remote to control Anki from your phone ['149004221', 2021-08-11T17:57, 'None', '']
    Batch Editing ['291119185', 2019-06-02T19:47, 'None', '']
    BetterSearch ['1052724801', 2021-12-05T02:24, 'None', '']
    BiDi Tools ['281067366', 2022-01-14T01:41, 'None', '']
    Browser Resizer ['1435775540', 2021-08-01T22:11, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2021-12-05T02:23, 'None', '']
    Change Interface Font ['1431333984', 2021-08-27T01:36, 'None', mod]
    Correct Answers Graph ['993120073', 2020-03-24T12:57, 'None', '']
    Countdown To Events and Exams ['1143540799', 2021-03-13T20:40, 'None', '']
    Deck name in title 21 ['699175524', 2019-06-01T02:05, 'None', '']
    Directly review without going through overview page ['1024346707', 2019-11-07T08:36, 'None', '']
    Edit Field During Review ['1020366288', 2020-10-07T13:22, 'None', '']
    Editor Live Preview ['1960039667', 2021-10-09T05:06, 'None', '']
    Field AutoComplete ['511710206', 2021-09-09T16:08, 'None', '']
    Fill the blanks - Multiple typecloze support ['1933645497', 2021-08-05T20:38, 'None', '']
    Flexible Duplicate Checking ['1587955871', 2020-05-19T07:49, 'None', '']
    Fluent Forever - Open Websites ['143682703', 2019-12-22T17:22, 'None', '']
    Highlight Color Shortcut ['1178291236', 2021-04-01T17:42, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T17:06, 'None', '']
    Image Editor ['307397307', 2021-12-19T11:58, 'None', '']
    Image Style Editor ['1593969147', 2021-12-17T07:01, 'None', mod]
    Keep model of add cards ['424778276', 2021-10-16T18:36, 'None', '']
    Limit new cards based on due  reviews ['548158563', 2021-06-09T07:26, 'None', '']
    Load Balanced Scheduler ['208879074', 2018-10-05T01:06, 'None', '']
    Markdown and KaTeX Support ['1087328706', 2021-11-12T08:34, 'None', '']
    Media Import ['1531997860', 2018-07-14T13:32, 'None', '']
    Merge Notes ['1425504015', 2022-01-21T11:48, 'None', '']
    Mindmap from tag hierarchy ['965278890', 2021-05-20T13:49, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T18:45, 'None', '']
    Minimize to tray ['85158043', 2021-12-13T16:59, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2021-01-27T09:09, 'None', '']
    More Overview Stats 21 ['738807903', 2021-07-30T20:13, 'None', '']
    Multiple Choice for Anki ['1566095810', 2021-03-18T17:50, 'None', '']
    Numeric Keypad Remapping  ease bugs fixed ['653807651', 2022-01-07T14:15, 'None', '']
    Open linked pdf docx epub audiovideo etc in external Program ['879473266', 2021-12-12T11:51, 'None', '']
    Opening the same window multiple time ['354407385', 2020-05-16T01:59, 'None', '']
    Paste Images As WebP ['1151815987', 2021-12-20T15:46, 'None', '']
    Preview Slideshow ['90397199', 2021-08-06T08:42, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T07:26, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-12-13T14:14, '20.12.13i151', '']
    Rendered Browser ['993394845', 2020-12-20T21:48, 'None', '']
    Replay buttons on card ['498789867', 2017-11-20T12:38, 'None', '']
    Reset Custom Study Limit Increases ['738867649', 2021-10-20T01:17, 'None', '']
    Review First ['181194973', 2019-03-06T17:47, 'None', '']
    Ruzu Pop-ups ['1736169259', 2021-03-08T18:00, 'v0.0.2', '']
    See Previous Card Ratings in Reviewer ['1906641654', 2021-08-19T22:32, 'None', '']
    Show total review count in main screen ['1730200873', 2020-07-25T15:06, 'None', mod]
    Show total time spent in main screen ['1238121460', 2020-07-19T09:36, 'None', '']
    Statistics for Note Types Card Types and Tags ['16703369', 2020-07-20T03:11, 'None', '']
    Stats Plus ['1009670238', 2021-03-04T12:23, 'None', '']
    Tab Indentation ['544286375', 2022-01-21T16:42, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-17T23:33, 'None', mod]
    Time per revised card graph ['1703703955', 2021-01-27T00:12, 'None', '']
    Tippy Tooltips ['1840818335', 2022-01-19T17:47, 'None', '']
    True Retention by Card Maturity Simplified ['1779060522', 2020-06-28T14:45, 'None', '']
    Word Shuffler - Sentences randomizer ['1190756458', 2021-03-30T22:45, 'None', '']
    Zzz legacy Dont Stop Currently Played Audio File ['726552056', 2020-07-15T09:47, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2021-12-05T20:28, 'None', '']

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.50 (81cc5a09) Python 3.10.1 Qt 5.15.2 PyQt 5.15.6
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-01-24 08:16:04
Add-ons possibly involved: ⁨Puppy Reinforcement, Numeric Keypad Remapping  ease bugs fixed⁩

Caught exception:
Traceback (most recent call last):
  File "/home/grim/.local/share/Anki2/addons21/653807651/__init__.py", line 113, in answerCaller
    return onAnswerButton(int(closureKey))
  File "/home/grim/.local/share/Anki2/addons21/653807651/__init__.py", line 92, in onAnswerButton
    self._answerCard(number)
  File "/home/grim/.local/share/Anki2/addons21/653807651/__init__.py", line 54, in newAnswerCard
    _oldAnswerCard(self, ease)
  File "/usr/lib/python3.10/site-packages/aqt/reviewer.py", line 430, in _answerCard
    self._after_answering(ease)
  File "/usr/lib/python3.10/site-packages/aqt/reviewer.py", line 433, in _after_answering
    gui_hooks.reviewer_did_answer_card(self, self.card, ease)
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 3172, in __call__
    hook(reviewer, card, ease)
  File "/home/grim/.local/share/Anki2/addons21/1722658993/reinforcer.py", line 75, in showDog
    self._showTooltip(encouragement, image_path)
  File "/home/grim/.local/share/Anki2/addons21/1722658993/reinforcer.py", line 86, in _showTooltip
    dogTooltip(
  File "/home/grim/.local/share/Anki2/addons21/1722658993/tooltip.py", line 91, in dogTooltip
    lab.move(aw.mapToGlobal(QPoint(0, -260 - vdiff + aw.height())))  # type:ignore
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 2 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'int'

```python

```

**Comment by Dazaisan99** [comment]
I tried to fix it , and I've come up with a solution (works on my machine I guess).
You can go into the Anki2 directory and change some things in _addons21/1722658993/tooltip.py_
In the dogTooltip function, I've created a QPoint variable, set its x and y values to what was in the weird function previously and replaced it with the variable.
The function now looks like this
```python
def dogTooltip(
    encouragement: str,
    image_path: str,
    count: int,
    image_height: int,
    color: str,
    duration: int,
    parent: QWidget = None,
):
    global _tooltipTimer, _tooltipLabel

    closeTooltip()
    aw = parent or mw.app.activeWindow() or mw
    lab = CustomLabel(
        f"""\
<table cellpadding=10>
<tr>
<td><img height={image_height} src="{image_path}"></td>
<td valign="middle">
    <center><b>{count} {'cards' if count > 1 else 'card'} done so far!</b><br>
    {encouragement}</center>
</td>
</tr>
</table>""",
        aw,
    )
    lab.setFrameStyle(QFrame.Panel)
    lab.setLineWidth(2)
    lab.setWindowFlags(Qt.ToolTip)
    p = QPalette()
    p.setColor(QPalette.Window, QColor(color))
    p.setColor(QPalette.WindowText, QColor("#000000"))
    lab.setPalette(p)
    vdiff = (image_height - 128) / 2
    point = QPoint()
    point.setX(int(0))
    point.setY(int(-260 - vdiff + aw.height()))
    lab.move(aw.mapToGlobal(point))  #0, (-260 - vdiff + aw.height()))))  # type:ignore
    lab.show()
    _tooltipTimer = mw.progress.timer(duration, closeTooltip, False)
    _tooltipLabel = lab
```

**Comment by glutanimate** [comment]
Thanks for the report! This will be fixed in the upcoming update on AnkiWeb.
