### ISSUE TITLE
[Puppy Reinforcement] alterations to images folder break image display on Windows

### ISSUE THREAD

**Issue by usnish** [glutanimate/puppy-reinforcement#4]
Hi! Have been messing around with the images folder, and have been able to remove / drop in any new JPG images on MacOS, but on Windows any alterations (including removing some of the existing puppy photos) have left the add-on non-functional (with the desired image being replaced by a white placeholder image).

Have tried re-starting Anki, deleting and re-downloading the plugin, and all, to no avail. Any idea what might be going on?

![28207643_10210315437105934_279507565_o](https://user-images.githubusercontent.com/706036/36287753-bf20a432-1284-11e8-84cc-f9eca31a85cd.jpg)

**Comment by glutanimate** [comment]
Should be fixed with ea7772fb5ce66f320de12ef871048b2eba1e14db
